### ISSUE TITLE
Negative Y offset settings underlay the Unicode codepoint display

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/hackover#2]
<img width="891" alt="overlap" src="https://cloud.githubusercontent.com/assets/4249591/11013534/74409204-84df-11e5-8fae-34e939b032a1.png">

**Comment by jublo** [comment]
@chrissimpkins Which solution would you prefer to see?

**Comment by chrissimpkins** [comment]
Probably best to shift the entire box upwards so that the glyphs both sit below the Unicode code point bars?
