### ISSUE TITLE
Settings bar position on zoom view

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/hackover#3]
Is it possible to attach the settings bar to the top of the page so that it is still in view and you can still use it when you drag down to glyphs on lower levels of the page in zoom view?

<img width="899" alt="settings" src="https://cloud.githubusercontent.com/assets/4249591/11013545/ff726b0e-84df-11e5-9331-9968f762d7fd.png">

**Comment by jublo** [comment]
@chrissimpkins Definitely possible.
